version: "3.7"

services:
  graphql:
    container_name: gita-graphql
    restart: always
    image: bhagavadgita/gita-graphql
    build:
      context: .
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 8081:8081
    command:
      [
        "--connection",
        "${DATABASE_URI}",
        "--port",
        "8081",
        "--schema",
        "public",
        "--cors",
        "--enhance-graphiql",
      ]

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

networks:
  network:

volumes:
  caddy_data:
  caddy_config:
