name: Deploy to VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Download source code
        uses: actions/checkout@v2

      - name: Set environment variables in the .env file
        run: |
          echo DATABASE_URI="${{ secrets.DATABASE_URI }}" > .env

      - name: Build docker images locally
        run: docker-compose -f docker-compose.prod.yml build --parallel

      - name: Stop previous running containers (if any)
        run: docker-compose -f docker-compose.prod.yml stop
        
      - name: Run the containers
        run: docker-compose -f docker-compose.prod.yml up -d
