name: Deploy to VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: cleanup and reset permissions to user from docker user
        run: chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: download source code
        uses: actions/checkout@v2

      - name: set environment variables in .env file
        run: |
          echo DATABASE_URI="${{ secrets.DATABASE_URI }}" > .env

      - name: build docker images locally
        run: docker-compose -f docker-compose.prod.yml build --parallel

      - name: run docker compose
        run: docker-compose -f docker-compose.prod.yml up -d
